public class Main {
    public static void main(String[] args) {
        System.out.println(" Задача 1 ");
        int apples = - 1452365;
        System.out.println(apples);
        byte potato = 100;
        System.out.println(potato);
        short oranges = 20000;
        System.out.println(oranges);
        long boards = 90000000;
        System.out.println(boards);
        float appleJuse = 3.4f;
        System.out.println(appleJuse);
        double milk = 45.42;
        System.out.println(milk);
        float a = 27.12f;
        System.out.println(a);
        long b = 987678965549L;
        System.out.println(b);
        double c = 2.786;
        System.out.println(c);
        boolean d = 2 > 3 ;
        System.out.println(d);
        short f = 569;
        System.out.println(f);
        short g = -159;
        System.out.println(g);
        short x = 27897;
        System.out.println(x);
        byte r = 67;
        System.out.println(r);
        short teacher1 = 23;
        short teacher2 = 27;
        short teacher3 = 30;
        System.out.println(teacher1);
        System.out.println(teacher2);
        System.out.println(teacher3);
        System.out.println(" Всего Учеников " + ( teacher1 + teacher2 + teacher3));
    short papper = 480;
        System.out.println(papper);
    int allStudents = teacher1+teacher2+teacher3;
        System.out.println(allStudents);
        System.out.println(" Бумаги на каждого ученика " + (papper / allStudents));
        System.out.println(" Задание 4 ");
    int outPutMinBottles = 16 / 2 ;
    int outPut20min = outPutMinBottles * 20 ;
        System.out.println(outPutMinBottles);
        System.out.println(outPut20min);
    int outPutHour = outPutMinBottles * 60;
    int outPutDay = outPutHour * 24;
    int outPut3Days = outPutDay * 3;
        System.out.println(outPutHour);
        System.out.println(outPutDay);
        System.out.println(outPut3Days);
    int outPutMonth = outPutDay * 30;
        System.out.println(outPutMonth);
        System.out.println("За 20 машины произвела бутылок " + outPut20min + " штук ");
        System.out.println(" За сутки машины произвели бутылок" + outPutDay + " штук ");
        System.out.println(" За 3 дня машины произвели бутылок " + outPut3Days + " штук ");
        System.out.println(" За месяц машины произвели бутылок " + outPutMonth + " штук ");
        System.out.println( " Задание 5 ");
    int totalJar = 120 ;
    int whiteJar = 2;
    int browneJar = 4;
    int totalJarClass = whiteJar + browneJar ;
    int totalClass = totalJar / totalJarClass ;
        System.out.println(totalJar);
        System.out.println( whiteJar);
        System.out.println(browneJar);
        System.out.println(totalJarClass);
        System.out.println(totalClass);
    int totalWhiteJar = whiteJar * totalClass;
    int totalBrownJar = browneJar * totalClass;
        System.out.println(totalWhiteJar);
        System.out.println(totalBrownJar);
        System.out.println(" В школе, где " + totalClass + " классов, нужно " + totalWhiteJar + " банок белой краски и " + totalBrownJar+ " банок коричневой краски " );}
}